
import java.text.DecimalFormat;
import java.util.ArrayList;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author tyrhi4976
 */
public class UnitConversionTest extends javax.swing.JFrame {
//array list for students marks
    ArrayList <Integer> marks = new ArrayList();
    double avg = 0;
    
    public UnitConversionTest() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jComboBox1 = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        incorrectQ2C2 = new javax.swing.JRadioButton();
        incorrectQ2C4 = new javax.swing.JRadioButton();
        incorrectQ3C1 = new javax.swing.JRadioButton();
        incorrectQ3C3 = new javax.swing.JRadioButton();
        incorrectQ3C2 = new javax.swing.JRadioButton();
        correctQ3C4 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        incorrectQ1C1 = new javax.swing.JRadioButton();
        incorrectQ1C3 = new javax.swing.JRadioButton();
        incorrectQ1C2 = new javax.swing.JRadioButton();
        correctQ1C4 = new javax.swing.JRadioButton();
        correctQ2C1 = new javax.swing.JRadioButton();
        incorrectQ2C3 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        correctQ6T = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        incorrectQ6F = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        correctQ4T = new javax.swing.JRadioButton();
        incorrectQ4F = new javax.swing.JRadioButton();
        incorrectQ5T = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        correctQ5F = new javax.swing.JRadioButton();
        getMarksButton = new javax.swing.JButton();
        homePageButton = new javax.swing.JButton();
        resultsLabel = new javax.swing.JLabel();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonGroup2.add(incorrectQ2C2);
        incorrectQ2C2.setText("1");
        incorrectQ2C2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                incorrectQ2C2ActionPerformed(evt);
            }
        });

        buttonGroup2.add(incorrectQ2C4);
        incorrectQ2C4.setText("3.333");
        incorrectQ2C4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                incorrectQ2C4ActionPerformed(evt);
            }
        });

        buttonGroup3.add(incorrectQ3C1);
        incorrectQ3C1.setText("780%");
        incorrectQ3C1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                incorrectQ3C1ActionPerformed(evt);
            }
        });

        buttonGroup3.add(incorrectQ3C3);
        incorrectQ3C3.setText("7.8%");
        incorrectQ3C3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                incorrectQ3C3ActionPerformed(evt);
            }
        });

        buttonGroup3.add(incorrectQ3C2);
        incorrectQ3C2.setText("78%");
        incorrectQ3C2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                incorrectQ3C2ActionPerformed(evt);
            }
        });

        buttonGroup3.add(correctQ3C4);
        correctQ3C4.setText("0.78%");
        correctQ3C4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                correctQ3C4ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Multiple Choice");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("1. What is 1/20th as a decimal?");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("2. What is 7/8 + 12/16 as a decimal?");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("3. What is .0078 as a percent?");

        buttonGroup1.add(incorrectQ1C1);
        incorrectQ1C1.setText("2.0");
        incorrectQ1C1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                incorrectQ1C1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(incorrectQ1C3);
        incorrectQ1C3.setText(".002");
        incorrectQ1C3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                incorrectQ1C3ActionPerformed(evt);
            }
        });

        buttonGroup1.add(incorrectQ1C2);
        incorrectQ1C2.setText("20");
        incorrectQ1C2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                incorrectQ1C2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(correctQ1C4);
        correctQ1C4.setText(".05");
        correctQ1C4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                correctQ1C4ActionPerformed(evt);
            }
        });

        buttonGroup2.add(correctQ2C1);
        correctQ2C1.setText("1.625");
        correctQ2C1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                correctQ2C1ActionPerformed(evt);
            }
        });

        buttonGroup2.add(incorrectQ2C3);
        incorrectQ2C3.setText("0.792");
        incorrectQ2C3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                incorrectQ2C3ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("5. 3' 5/6\" + 4' 1/2\" = 7' 7/6\"");

        correctQ6T.setText("True");
        correctQ6T.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                correctQ6TActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("6. There are 24 890 mL in 24.89L");

        incorrectQ6F.setText("False");
        incorrectQ6F.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                incorrectQ6FActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("True or False");

        correctQ4T.setText("True");
        correctQ4T.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                correctQ4TActionPerformed(evt);
            }
        });

        incorrectQ4F.setText("False");
        incorrectQ4F.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                incorrectQ4FActionPerformed(evt);
            }
        });

        incorrectQ5T.setText("True");
        incorrectQ5T.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                incorrectQ5TActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("4. There are 1000g in a Kg");

        correctQ5F.setText("False");
        correctQ5F.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                correctQ5FActionPerformed(evt);
            }
        });

        getMarksButton.setText("Get Marks");
        getMarksButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getMarksButtonActionPerformed(evt);
            }
        });

        homePageButton.setText("Back to Home Page");
        homePageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homePageButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(correctQ2C1)
                            .addComponent(incorrectQ2C3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(incorrectQ3C3)
                                                    .addComponent(incorrectQ3C1))
                                                .addGap(64, 64, 64)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(correctQ3C4)
                                                    .addComponent(incorrectQ3C2)))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(48, 48, 48)
                                                .addComponent(jLabel4)))
                                        .addGap(114, 114, 114))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(resultsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(correctQ4T)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(incorrectQ4F))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(correctQ6T)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(incorrectQ6F)
                                        .addGap(33, 33, 33))
                                    .addComponent(jLabel8)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(42, 42, 42)
                                        .addComponent(jLabel7)))))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(incorrectQ1C3)
                                    .addComponent(incorrectQ1C1))
                                .addGap(66, 66, 66)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(incorrectQ1C2)
                                    .addComponent(correctQ1C4)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(incorrectQ2C2)
                                            .addComponent(incorrectQ2C4))
                                        .addGap(124, 124, 124)
                                        .addComponent(incorrectQ5T)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(correctQ5F)))
                                .addGap(54, 54, 54))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(309, 309, 309))))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(getMarksButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(homePageButton)
                .addGap(33, 33, 33))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(incorrectQ1C1)
                            .addComponent(incorrectQ1C2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(incorrectQ1C3)
                            .addComponent(correctQ1C4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(correctQ2C1)
                            .addComponent(incorrectQ2C2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(incorrectQ2C3)
                            .addComponent(incorrectQ2C4))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(incorrectQ3C2)
                            .addComponent(incorrectQ3C1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(incorrectQ3C3)
                            .addComponent(correctQ3C4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(resultsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(getMarksButton)
                                .addComponent(homePageButton))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(correctQ5F)
                                    .addComponent(incorrectQ5T, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(correctQ4T)
                                    .addComponent(incorrectQ4F))
                                .addGap(112, 112, 112)
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(correctQ6T)
                                    .addComponent(incorrectQ6F))))))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void incorrectQ2C2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_incorrectQ2C2ActionPerformed
        correctQ2C1.setEnabled(false);
        incorrectQ2C2.setEnabled(false);
        incorrectQ2C3.setEnabled(false);
        incorrectQ2C4.setEnabled(false);
        marks.add(0);
        System.out.println(marks);
    }//GEN-LAST:event_incorrectQ2C2ActionPerformed

    private void incorrectQ3C3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_incorrectQ3C3ActionPerformed
        incorrectQ3C1.setEnabled(false);
        incorrectQ3C2.setEnabled(false);
        incorrectQ3C3.setEnabled(false);
        correctQ3C4.setEnabled(false);
        marks.add(0);
        System.out.println(marks);
    }//GEN-LAST:event_incorrectQ3C3ActionPerformed

    private void incorrectQ1C3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_incorrectQ1C3ActionPerformed
        incorrectQ1C1.setEnabled(false);
        incorrectQ1C2.setEnabled(false);
        incorrectQ1C3.setEnabled(false);
        correctQ1C4.setEnabled(false);
        marks.add(0);
        System.out.println(marks);
    }//GEN-LAST:event_incorrectQ1C3ActionPerformed

    private void incorrectQ1C2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_incorrectQ1C2ActionPerformed
        incorrectQ1C1.setEnabled(false);
        incorrectQ1C2.setEnabled(false);
        incorrectQ1C3.setEnabled(false);
        correctQ1C4.setEnabled(false);
        marks.add(0);
        System.out.println(marks);    }//GEN-LAST:event_incorrectQ1C2ActionPerformed

    private void correctQ1C4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_correctQ1C4ActionPerformed
        incorrectQ1C1.setEnabled(false);
        incorrectQ1C2.setEnabled(false);
        incorrectQ1C3.setEnabled(false);
        correctQ1C4.setEnabled(false);
        marks.add(1);
        System.out.println(marks);    }//GEN-LAST:event_correctQ1C4ActionPerformed

    private void incorrectQ2C3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_incorrectQ2C3ActionPerformed
correctQ2C1.setEnabled(false);
        incorrectQ2C2.setEnabled(false);
        incorrectQ2C3.setEnabled(false);
        incorrectQ2C4.setEnabled(false);
        marks.add(0);
        System.out.println(marks);    }//GEN-LAST:event_incorrectQ2C3ActionPerformed

    private void incorrectQ2C4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_incorrectQ2C4ActionPerformed
correctQ2C1.setEnabled(false);
        incorrectQ2C2.setEnabled(false);
        incorrectQ2C3.setEnabled(false);
        incorrectQ2C4.setEnabled(false);
        marks.add(0);
        System.out.println(marks);    }//GEN-LAST:event_incorrectQ2C4ActionPerformed

    private void incorrectQ3C1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_incorrectQ3C1ActionPerformed
incorrectQ3C1.setEnabled(false);
        incorrectQ3C2.setEnabled(false);
        incorrectQ3C3.setEnabled(false);
        correctQ3C4.setEnabled(false);
        marks.add(0);
        System.out.println(marks);    }//GEN-LAST:event_incorrectQ3C1ActionPerformed

    private void incorrectQ6FActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_incorrectQ6FActionPerformed
        incorrectQ6F.setEnabled(false);
        correctQ6T.setEnabled(false);
        marks.add(0);
        System.out.println(marks); 
    }//GEN-LAST:event_incorrectQ6FActionPerformed

    private void correctQ4TActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_correctQ4TActionPerformed
        correctQ4T.setEnabled(false);
        incorrectQ4F.setEnabled(false);
        marks.add(1);
        System.out.println(marks);     }//GEN-LAST:event_correctQ4TActionPerformed

    private void incorrectQ4FActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_incorrectQ4FActionPerformed
        correctQ4T.setEnabled(false);
        incorrectQ4F.setEnabled(false);
        marks.add(0);
        System.out.println(marks);     }//GEN-LAST:event_incorrectQ4FActionPerformed

    private void incorrectQ5TActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_incorrectQ5TActionPerformed
        incorrectQ5T.setEnabled(false);
        correctQ5F.setEnabled(false);
        marks.add(0);
        System.out.println(marks);     }//GEN-LAST:event_incorrectQ5TActionPerformed

    private void correctQ5FActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_correctQ5FActionPerformed
        incorrectQ5T.setEnabled(false);
        correctQ5F.setEnabled(false);
        marks.add(1);
        System.out.println(marks);     }//GEN-LAST:event_correctQ5FActionPerformed

    private void homePageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homePageButtonActionPerformed
         this.setVisible(false);
         new HomeScreen().setVisible(true);
    }//GEN-LAST:event_homePageButtonActionPerformed

    private void getMarksButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getMarksButtonActionPerformed
        double sum = 0;
        double avg = 0;
        double percent = 0;
        DecimalFormat x = new DecimalFormat ("###");
                 
        for(int i=0; i < marks.size(); i++) {
          
            sum += marks.get(i);            
            avg = sum/6;
            percent = avg * 100;
        }
        
        
        resultsLabel.setText("You got a: %" + x.format(percent));
    }//GEN-LAST:event_getMarksButtonActionPerformed

    private void incorrectQ1C1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_incorrectQ1C1ActionPerformed
        incorrectQ1C1.setEnabled(false);
        incorrectQ1C2.setEnabled(false);
        incorrectQ1C3.setEnabled(false);
        correctQ1C4.setEnabled(false);
        marks.add(1);
        System.out.println(marks);    
    }//GEN-LAST:event_incorrectQ1C1ActionPerformed

    private void correctQ2C1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_correctQ2C1ActionPerformed
        correctQ2C1.setEnabled(false);
        incorrectQ2C2.setEnabled(false);
        incorrectQ2C3.setEnabled(false);
        incorrectQ2C4.setEnabled(false);
        marks.add(1);
        System.out.println(marks);    }//GEN-LAST:event_correctQ2C1ActionPerformed

    private void incorrectQ3C2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_incorrectQ3C2ActionPerformed
        incorrectQ3C1.setEnabled(false);
        incorrectQ3C2.setEnabled(false);
        incorrectQ3C3.setEnabled(false);
        correctQ3C4.setEnabled(false);
        marks.add(0);
        System.out.println(marks);    }//GEN-LAST:event_incorrectQ3C2ActionPerformed

    private void correctQ3C4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_correctQ3C4ActionPerformed
        incorrectQ3C1.setEnabled(false);
        incorrectQ3C2.setEnabled(false);
        incorrectQ3C3.setEnabled(false);
        correctQ3C4.setEnabled(false);
        marks.add(1);
        System.out.println(marks);    }//GEN-LAST:event_correctQ3C4ActionPerformed

    private void correctQ6TActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_correctQ6TActionPerformed
        correctQ6T.setEnabled(false);
        incorrectQ6F.setEnabled(false);
        marks.add(1);
        System.out.println(marks);    
    }//GEN-LAST:event_correctQ6TActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UnitConversionTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UnitConversionTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UnitConversionTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UnitConversionTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UnitConversionTest().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JRadioButton correctQ1C4;
    private javax.swing.JRadioButton correctQ2C1;
    private javax.swing.JRadioButton correctQ3C4;
    private javax.swing.JRadioButton correctQ4T;
    private javax.swing.JRadioButton correctQ5F;
    private javax.swing.JRadioButton correctQ6T;
    private javax.swing.JButton getMarksButton;
    private javax.swing.JButton homePageButton;
    private javax.swing.JRadioButton incorrectQ1C1;
    private javax.swing.JRadioButton incorrectQ1C2;
    private javax.swing.JRadioButton incorrectQ1C3;
    private javax.swing.JRadioButton incorrectQ2C2;
    private javax.swing.JRadioButton incorrectQ2C3;
    private javax.swing.JRadioButton incorrectQ2C4;
    private javax.swing.JRadioButton incorrectQ3C1;
    private javax.swing.JRadioButton incorrectQ3C2;
    private javax.swing.JRadioButton incorrectQ3C3;
    private javax.swing.JRadioButton incorrectQ4F;
    private javax.swing.JRadioButton incorrectQ5T;
    private javax.swing.JRadioButton incorrectQ6F;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel resultsLabel;
    // End of variables declaration//GEN-END:variables
}
